# Generated by Django 5.2 on 2025-06-11 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=100)),
                ('keywords', models.JSONField(default=list)),
                ('response_template', models.TextField()),
                ('requires_products', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('categories_interested', models.ManyToManyField(blank=True, to='products.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response'), ('system', 'System Message')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('intent_detected', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('products_recommended', models.ManyToManyField(blank=True, to='products.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.FloatField()),
                ('reason', models.TextField()),
                ('was_clicked', models.BooleanField(default=False)),
                ('was_added_to_cart', models.BooleanField(default=False)),
                ('was_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['-recommendation_score'],
            },
        ),
        migrations.CreateModel(
            name='SessionProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('interest_level', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession')),
            ],
            options={
                'unique_together': {('session', 'product')},
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='products_viewed',
            field=models.ManyToManyField(blank=True, through='chatbot.SessionProductView', to='products.product'),
        ),
        migrations.CreateModel(
            name='UserPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shopping_frequency', models.CharField(default='occasional', max_length=20)),
                ('preferred_brands', models.JSONField(blank=True, default=list)),
                ('style_preferences', models.JSONField(blank=True, default=dict)),
                ('preference_vector', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('favorite_categories', models.ManyToManyField(blank=True, to='products.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
