# Generated by Django 5.2 on 2025-06-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_behavioranalytics_customerbehaviorprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='detected_intent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query_type',
            field=models.CharField(choices=[('text_search', 'Text Search'), ('voice_search', 'Voice Search'), ('filter_search', 'Filter Search'), ('category_search', 'Category Search')], default='text_search', max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionproductclick',
            name='click_source',
            field=models.CharField(choices=[('search_result', 'Search Result'), ('recommendation', 'Chatbot Recommendation'), ('category_browse', 'Category Browse'), ('related_product', 'Related Product'), ('chat_mention', 'Mentioned in Chat')], max_length=100),
        ),
    ]
