# Generated by Django 5.2 on 2025-06-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_searchquery_detected_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='detected_intent',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
