# Generated by Django 5.2.3 on 2025-06-16 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail_level', models.CharField(choices=[('low', 'Low Detail'), ('medium', 'Medium Detail'), ('high', 'High Detail')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('stage', models.CharField(blank=True, max_length=50)),
                ('progress', models.FloatField(default=0.0)),
                ('message', models.TextField(blank=True)),
                ('estimated_time_remaining', models.CharField(blank=True, max_length=50)),
                ('generated_model_file', models.FileField(blank=True, null=True, upload_to='generated_models/')),
                ('polygon_count', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('progress', models.FloatField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='ai_3d_generation.generationrequest')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GenerationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='generation_images/')),
                ('angle', models.CharField(choices=[('front', 'Front View'), ('back', 'Back View'), ('left', 'Left Side'), ('right', 'Right Side'), ('top', 'Top View'), ('bottom', 'Bottom View'), ('angle_1', 'Angle 1'), ('angle_2', 'Angle 2')], max_length=20)),
                ('detected_angle', models.CharField(blank=True, choices=[('front', 'Front View'), ('back', 'Back View'), ('left', 'Left Side'), ('right', 'Right Side'), ('top', 'Top View'), ('bottom', 'Bottom View'), ('angle_1', 'Angle 1'), ('angle_2', 'Angle 2')], max_length=20, null=True)),
                ('order', models.IntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ai_3d_generation.generationrequest')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
