# Generated by Django 5.1.6 on 2025-06-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='angle_tag',
            field=models.CharField(blank=True, help_text="Tag for 3D generation, e.g., 'front', 'top'.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.FileField(upload_to='product_images/'),
        ),
    ]
