FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Install system dependencies for Python builds
RUN apt-get update && \
    apt-get install -y python3-distutils build-essential gcc && \
    rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the rest of the project
COPY . .

# Expose the port Django will run on
EXPOSE 8000

# Default command to run Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
