# Generated by Django 4.2.16 on 2025-07-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage_angle_tag_alter_productimage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('model', '3D Model'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
