# Generated by Django 5.2 on 2025-06-14 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('products', '0004_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_searches', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_recommendations', models.IntegerField(default=0)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('search_to_click_ratio', models.FloatField(default=0.0)),
                ('recommendation_click_rate', models.FloatField(default=0.0)),
                ('top_search_keywords', models.JSONField(blank=True, default=list)),
                ('top_categories', models.JSONField(blank=True, default=list)),
                ('peak_hours', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='CustomerBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_searches', models.IntegerField(default=0)),
                ('average_search_length', models.FloatField(default=0.0)),
                ('most_searched_keywords', models.JSONField(blank=True, default=list)),
                ('search_to_click_ratio', models.FloatField(default=0.0)),
                ('total_product_views', models.IntegerField(default=0)),
                ('total_product_clicks', models.IntegerField(default=0)),
                ('average_time_per_product', models.DurationField(blank=True, null=True)),
                ('click_to_cart_ratio', models.FloatField(default=0.0)),
                ('preferred_categories', models.JSONField(blank=True, default=dict)),
                ('avoided_categories', models.JSONField(blank=True, default=list)),
                ('average_price_viewed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_sensitivity_score', models.FloatField(default=0.5)),
                ('preferred_price_range', models.JSONField(blank=True, default=dict)),
                ('preferred_shopping_times', models.JSONField(blank=True, default=dict)),
                ('session_frequency', models.CharField(default='occasional', max_length=20)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('recommendation_acceptance_rate', models.FloatField(default=0.0)),
                ('chat_responsiveness', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_points_count', models.IntegerField(default=0)),
                ('confidence_level', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('query_timestamp', models.DateTimeField(auto_now_add=True)),
                ('query_type', models.CharField(choices=[('text_search', 'Text Search'), ('voice_search', 'Voice Search'), ('filter_search', 'Filter Search'), ('category_search', 'Category Search')], default='text_search', max_length=50)),
                ('results_count', models.IntegerField(default=0)),
                ('results_clicked', models.IntegerField(default=0)),
                ('first_click_position', models.IntegerField(blank=True, null=True)),
                ('extracted_keywords', models.JSONField(blank=True, default=list)),
                ('detected_intent', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('price_filter_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_filter_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category_filters', models.JSONField(blank=True, default=list)),
                ('brand_filters', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-query_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SessionProductClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('click_source', models.CharField(choices=[('search_result', 'Search Result'), ('recommendation', 'Chatbot Recommendation'), ('category_browse', 'Category Browse'), ('related_product', 'Related Product'), ('chat_mention', 'Mentioned in Chat')], max_length=50)),
                ('click_position', models.IntegerField(blank=True, null=True)),
                ('added_to_cart', models.BooleanField(default=False)),
                ('time_on_product_page', models.DurationField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.DeleteModel(
            name='ChatbotKnowledgeBase',
        ),
        migrations.AlterModelOptions(
            name='sessionproductview',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.RenameField(
            model_name='productrecommendation',
            old_name='created_at',
            new_name='shown_at',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='contains_category_mention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='contains_price_mention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='contains_search_intent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='average_price_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='behavioral_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='search_queries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_searches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='position_in_list',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('content_based', 'Content-Based'), ('collaborative', 'Collaborative Filtering'), ('popular', 'Popular Items'), ('behavioral', 'Behavioral Pattern'), ('hybrid', 'Hybrid Approach')], default='hybrid', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='time_on_product',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='time_to_click',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='user_feedback',
            field=models.CharField(blank=True, choices=[('helpful', 'Helpful'), ('not_relevant', 'Not Relevant'), ('too_expensive', 'Too Expensive'), ('not_interested', 'Not Interested')], max_length=20),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='was_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionproductview',
            name='came_from_recommendation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionproductview',
            name='came_from_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionproductview',
            name='view_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_searches', to='chatbot.chatsession'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionproductclick',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='products_clicked',
            field=models.ManyToManyField(blank=True, related_name='clicked_in_sessions', through='chatbot.SessionProductClick', to='products.product'),
        ),
        migrations.DeleteModel(
            name='UserPreferenceProfile',
        ),
    ]
